"""empty message

Revision ID: a21714011c3a
Revises: b6fcf266fa88
Create Date: 2023-04-22 09:27:42.459553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a21714011c3a'
down_revision = 'b6fcf266fa88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('list_locations', schema=None) as batch_op:
        batch_op.alter_column('list_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('location_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('list_locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))
        batch_op.alter_column('location_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('list_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
